# IP Spoofing Protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Disable Source Routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0

# Disable ICMP Redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0

# Ignore Broadcast Requests
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Log Suspicious Packets
net.ipv4.conf.all.log_martians = 1

# TCP SYN Cookies
net.ipv4.tcp_syncookies = 1